server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: country-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/country/**
        - id: player-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/player/**
        - id: season-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/season/**
        - id: team-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/team/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
